task1:
  model_type: "bert"
  model_path: "bert-base-uncased"
  task_name: "RTE"
  glue_dir: "data/glue_data"
  max_seq_length: 128
  per_gpu_train_batch_size: 32
  learning_rate: 2e-5
  num_train_epochs: 3.0
task2:
  model_type: "bert"
  model_path: "bert-base-uncased"
  task_name: "QQP"
  glue_dir: "data/glue_data"
  max_seq_length: 128
  per_gpu_train_batch_size: 32
  learning_rate: 2e-5
  num_train_epochs: 3.0
task3:
  model_type: "bert"
  model_path: "bert-base-uncased"
  task_name: "CoLA"
  glue_dir: "data/glue_data"
  max_seq_length: 128
  per_gpu_train_batch_size: 32
  learning_rate: 2e-5
  num_train_epochs: 3.0